### ISSUE TITLE
gemc exits with error=139 (Segmentation fault) intermittently

### ISSUE THREAD

**Issue by mariakzurek** [gemc/sci-g#1]
While working on my fork of this repo, I noticed that running `gemc` would sometimes fail with the following error (or similar):

```text
free(): double free detected in tcache 2
/__w/_temp/e93eb694-1e89-442a-8c93-554777f941e2.sh: line 5:   193 Segmentation fault      (core dumped) gemc example.jcard
```

For an example of the same job failing and succeeding without any other changes in the code being run, see e.g. https://github.com/mariakzurek/sci-g/runs/3878696656?check_suite_focus=true and https://github.com/mariakzurek/sci-g/runs/3878724293?check_suite_focus=true

The error seems to be intermittent/random, and re-running the job on the same commit a few times results in the job eventually succeeding. I'm not sure if this is related to a particular gcard or example since I don't have enough "statistics".

**Comment by maureeungaro** [comment]
These crashes happen randomly when geometry check is requested with /geometry/test/run (checkOverlaps = 2).

Looks like this is a geant4 problem happening when a separate thread is asked to delete the geometry. 

For the moment the only way to keep the overlap check in CI is to request to run on a single core. Keeping this issue open to check if it persist with new versions of geant4.

**Comment by maureeungaro** [comment]
Single core running address this issue. Can try again with geant4 11.
